name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version to release"
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            extension: ".tar.gz"
            system_name: "linux"
          - os: macos-latest
            extension: ".tar.gz"
            system_name: "macos"
          - os: windows-latest
            extension: ".zip"
            system_name: "windows"

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Rust environment
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}
      # Build Rust backend
      - name: Build
        run: |
          cargo build --release
          mv target/release/ping-server-rs${{ matrix.os == 'windows-latest' && '.exe' || ''}} ping-server-rs-${{ matrix.os }}${{ matrix.os == 'windows-latest' && '.exe' || ''}}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ping-server-rs-${{ matrix.os }}
          path: ./ping-server-rs-${{ matrix.os }}${{ matrix.os == 'windows-latest' && '.exe' || ''}}
  Upload-Release:
    permissions: write-all
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: output/
          merge-multiple: true
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*
          tag_name: ${{ github.event.inputs.version }}
